In [7]:
import numpy as np

A = np.array([
    [ 1,      1/6,    0,      1/6,   -2/3,    0,      0,     -2/3,    0     ],
    [ 1/6,    1,      1/6,    0,     -2/3,   -2/3,    0,      0,      0     ],
    [ 0,      1/6,    1,      1/6,    0,     -2/3,   -2/3,    0,      0     ],
    [ 1/6,    0,      1/6,    1,      0,      0,     -2/3,   -2/3,    0     ],
    [-2/3,   -2/3,    0,      0,      8/3,    0,      0,      0,     -4/3   ],
    [ 0,     -2/3,   -2/3,    0,      0,      8/3,    0,      0,     -4/3   ],
    [ 0,      0,     -2/3,   -2/3,    0,      0,      8/3,    0,     -4/3   ],
    [-2/3,    0,      0,     -2/3,    0,      0,      0,      8/3,   -4/3   ],
    [ 0,      0,      0,      0,     -4/3,   -4/3,   -4/3,   -4/3,   16/3   ]
], dtype=float)

f = np.array([0,0,0,0,1/6,1/6,1/6,1/6,1/3], dtype=float)

# ------------------------------------------------------------
# Punktfixierung:
# phi_9 = 0
# ------------------------------------------------------------

fixed_dof = 8

A_sub = A[0:8,0:8]
f_sub = f[0:8]
# A_mod = A.copy()
# f_mod = f.copy()

# A_mod[8, :] = 0
# A_mod[:, 8] = 0
print(np.round(A_sub,2))
# A_mod[fixed_dof, fixed_dof] = 1

# f_mod[fixed_dof] = 0
print(np.round(f_sub,2))

# ------------------------------------------------------------
# Lösen
# ------------------------------------------------------------

u = np.linalg.solve(A_sub, f_sub)

# ------------------------------------------------------------
# Ausgabe
# ------------------------------------------------------------

np.set_printoptions(precision=6, suppress=True)

print("Lösung u:")
print(u)

[[ 1.    0.17  0.    0.17 -0.67  0.    0.   -0.67]
 [ 0.17  1.    0.17  0.   -0.67 -0.67  0.    0.  ]
 [ 0.    0.17  1.    0.17  0.   -0.67 -0.67  0.  ]
 [ 0.17  0.    0.17  1.    0.    0.   -0.67 -0.67]
 [-0.67 -0.67  0.    0.    2.67  0.    0.    0.  ]
 [ 0.   -0.67 -0.67  0.    0.    2.67  0.    0.  ]
 [ 0.    0.   -0.67 -0.67  0.    0.    2.67  0.  ]
 [-0.67  0.    0.   -0.67  0.    0.    0.    2.67]]
[0.   0.   0.   0.   0.17 0.17 0.17 0.17]
Lösung u:
[0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125]
